chore: add a push retry if failed

diff --git a/.github/workflows/update-gitops-repo.yml b/.github/workflows/update-gitops-repo.yml
--- a/.github/workflows/update-gitops-repo.yml
+++ b/.github/workflows/update-gitops-repo.yml
@@ -39,3 +39,9 @@ jobs:
           git add values.yaml
           git commit -m "chore(cd): update image"
           git push
+          if [ $? -ne 0 ]; then
+            echo "Push failed, retrying..."
+            git config pull.rebase false
+            git pull
+            git push
+          fi
